# This is a sample build configuration for .NET Core.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: mono

pipelines:
  default:
    - step:
        script:
          - apt-get update
          - apt-get install -y zip
          - nuget restore
          - MONO_IOMAP=case xbuild /t:Build /p:Configuration="Release" /p:Platform="Any CPU" Serializer.sln
          - cd /opt/atlassian/pipelines/agent/build/Serializer.Logic/bin/Release/
          - mkdir dist
          - zip dist/${BITBUCKET_REPO_SLUG}.zip TI.Serializer.Logic.dll TI.Serializer.Logic.pdb 
          - curl -s --user "${BB_AUTH_STRING}" -X POST "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" -F files=@"dist/${BITBUCKET_REPO_SLUG}.zip"